### ISSUE TITLE
graphql-portal-docker_gql-portal-dashboard container errors out

### ISSUE THREAD

**Issue by JJediny** [GraphQL-Portal/graphql-portal-docker#2]
$ docker-compose -f docker-compose.yml up
```
Creating network "graphql-portal-docker_graphql-portal" with the default driver
Creating graphql-portal-docker_gql-portal-mongo_1 ... done
Creating graphql-portal-docker_gql-portal-redis_1 ... done
Creating graphql-portal-docker_gql-portal-dashboard_1 ... done

ERROR: for gql-portal-gateway  Container "f6e796f3b973" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```
$ docker logs f6e796f3b973
```
yarn run v1.22.5
$ yarn workspace graphql-portal-dashboard-backend start:prod
$ node dist/main
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: /usr/app/packages/backend/config/env/production.json: Unexpected string in JSON at position 203
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at _ifElse (/usr/app/node_modules/ramda/src/ifElse.js:39:54)
    at f1 (/usr/app/node_modules/ramda/src/internal/_curry1.js:19:17)
    at XWrap.f (/usr/app/node_modules/ramda/src/mapObjIndexed.js:39:16)
    at XWrap.@@transducer/step (/usr/app/node_modules/ramda/src/internal/_xwrap.js:17:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.5/lib/cli.js start:prod
Directory: /usr/app/packages/backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by valcker** [comment]
Hi @JJediny , this is due to the recent update in graphql-portal-dashboard itself. I will push the fix in a couple of hours.

**Comment by valcker** [comment]
@JJediny the most [recent release](https://github.com/GraphQL-Portal/graphql-portal-dashboard/commit/db49524947fe979f0ae627481c57764b1a387814) fixes the issue. You'll have to update the docker image locally.

**Comment by valcker** [comment]
Hey @JJediny ,

Just checking if the latest image fixes the problem for you?

**Comment by JJediny** [comment]
@valcker Sorry I was offline last week.

Running `docker-compose pull gql-portal-dashboard` and re-running `docker-compose -f docker-compose.yml up` - everything is working now, thanks much!

<img width="1347" alt="Screen Shot 2021-02-01 at 8 22 41 PM" src="https://user-images.githubusercontent.com/6350035/106539339-cae3d680-64cb-11eb-8b82-505c79c5f40b.png">
