### ISSUE TITLE
gql-portal-dashboard is crashing on start

### ISSUE THREAD

**Issue by anthu** [GraphQL-Portal/graphql-portal-docker#5]
Running `docker compose up` on the latest main the gql-portal-dashboard is crashing on launch:

Am I missing something?

```
gql-portal-dashboard_1  | [0] UPDATE AVAILABLE The latest version of `serve` is 12.0.0
gql-portal-dashboard_1  | [1] yarn workspace v1.22.5
gql-portal-dashboard_1  | [0] INFO: Accepting connections at http://localhost:8080
gql-portal-dashboard_1  | [1] yarn run v1.22.5
gql-portal-dashboard_1  | [1] $ ts-node node_modules/.bin/migrate-mongo up -f migrate-mongo-config.ts
gql-portal-dashboard_1  | [1] ERROR: Could not migrate up 20210318170210-cipher-setup.ts: ⨯ Unable to compile TypeScript:
gql-portal-dashboard_1  | [1] src/data/migrations/20210318170210-cipher-setup.ts(30,30): error TS2550: Property 'flat' does not exist on type 'Promise<UpdateWriteOpResult>[][]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
gql-portal-dashboard_1  | [1]  TSError: ⨯ Unable to compile TypeScript:
gql-portal-dashboard_1  | [1] src/data/migrations/20210318170210-cipher-setup.ts(30,30): error TS2550: Property 'flat' does not exist on type 'Promise<UpdateWriteOpResult>[][]'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.
gql-portal-dashboard_1  | [1]
gql-portal-dashboard_1  | [1]     at createTSError (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:587:12)
gql-portal-dashboard_1  | [1]     at reportTSError (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:591:19)
gql-portal-dashboard_1  | [1]     at getOutput (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:921:36)
gql-portal-dashboard_1  | [1]     at Object.compile (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:1189:32)
gql-portal-dashboard_1  | [1]     at Module.m._compile (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:1295:42)
gql-portal-dashboard_1  | [1]     at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
gql-portal-dashboard_1  | [1]     at Object.require.extensions.<computed> [as .ts] (/usr/app/packages/backend/node_modules/ts-node/src/index.ts:1298:12)
gql-portal-dashboard_1  | [1]     at Module.load (internal/modules/cjs/loader.js:933:32)
gql-portal-dashboard_1  | [1]     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
gql-portal-dashboard_1  | [1]     at Module.require (internal/modules/cjs/loader.js:957:19)
gql-portal-dashboard_1  | [1] error Command failed with exit code 1.
gql-portal-dashboard_1  | [1] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gql-portal-dashboard_1  | [1] error Command failed.
gql-portal-dashboard_1  | [1] Exit code: 1
gql-portal-dashboard_1  | [1] Command: /usr/local/bin/node
gql-portal-dashboard_1  | [1] Arguments: /opt/yarn-v1.22.5/lib/cli.js migrate
gql-portal-dashboard_1  | [1] Directory: /usr/app/packages/backend
gql-portal-dashboard_1  | [1] Output:
gql-portal-dashboard_1  | [1]
gql-portal-dashboard_1  | [1] info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
gql-portal-dashboard_1  | [1] yarn workspace graphql-portal-dashboard-backend migrate && yarn start:prod exited with code 1
gql-portal-dashboard_1  | --> Sending SIGTERM to other processes..
gql-portal-dashboard_1  | [0]
gql-portal-dashboard_1  | [0] INFO: Gracefully shutting down. Please wait...
gql-portal-dashboard_1  | [0] serve -s packages/frontend/build -l 8080 exited with code 0
gql-portal-dashboard_1 exited with code 1
```

**Comment by msadovyi** [comment]
Hi, @anthu! It has been fixed, try to pull latest image :)
Thanks!

**Comment by anthu** [comment]
Hey Max,
Thanks - that fixed it for me.
